### ISSUE TITLE
[FEATURE] Display full process checklist numbering on UI

### ISSUE THREAD

**Issue by kimeetok** [aiverify-foundation/aiverify#291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

To display the full numbering in the process checklist UI, similar to how it is displayed in the summary report. (i.e. x.y.z instead of y.z)

As-is:
![image](https://github.com/aiverify-foundation/aiverify/assets/129362897/e578d5ed-3882-4018-8627-90d247a66142)

To-be:
![image](https://github.com/aiverify-foundation/aiverify/assets/129362897/88ab7606-4be1-4a53-a4a6-fe030ae4b36b)

### Additional Context

To support the recent mapping of AI Verify framework to ISO/IEC 42001 and future mapping exercises, we want to allow users of the AI Verify Toolkit to easily reference specific process checks listed in the crosswalk. 

### Related Issues/PRs

#287

**Comment by imda-benedictlee** [comment]
Issue has been fixed. Closing this issue.
